//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Somokati
    {
        public int ID { get; set; }
        public string photo { get; set; }
        public string model { get; set; }
        public string opisanie { get; set; }
        public string price { get; set; }
        public string adress_mest { get; set; }
        public int nalichie { get; set; }
        public int arenduet { get; set; }
    }
}
