//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class tochka_prokata
    {
        public int ID { get; set; }
        public string name_punkt { get; set; }
        public string gorod { get; set; }
        public string adress { get; set; }
        public string phone { get; set; }
    }
}
