//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int ID { get; set; }
        public string surname { get; set; }
        public string name { get; set; }
        public string otchestvo { get; set; }
        public int role2 { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public Nullable<int> count { get; set; }
        public Nullable<bool> active { get; set; }
    
        public virtual Role Role { get; set; }
    }
}
